"""Family-calls dashboard: call activity between Sahmoud and his parents
(Hanan / mom and Hatem / dad), seeded from the offline Facebook/Messenger export.
Static data.json generated by chat-assistant/scripts/family_calls_build.py.
Private (Tailscale) -- it's personal family call history."""
import json
import os
from pathlib import Path
from flask import Flask, send_from_directory, jsonify

HERE = Path(__file__).resolve().parent
STATIC_DIR = HERE / "static"
APPLICATION_ROOT = os.environ.get("APPLICATION_ROOT", "")

app = Flask(__name__)
app.config["APPLICATION_ROOT"] = APPLICATION_ROOT


@app.get("/")
def index():
    return send_from_directory(str(STATIC_DIR), "index.html")


@app.get("/healthz")
def healthz():
    return {"ok": True, "app": "mom-calls"}


@app.get("/data.json")
def data():
    p = STATIC_DIR / "data.json"
    if p.exists():
        return jsonify(json.loads(p.read_text(encoding="utf-8")))
    return jsonify({"error": "no data"}), 404


@app.get("/<path:fn>")
def static_files(fn):
    return send_from_directory(str(STATIC_DIR), fn)


if __name__ == "__main__":
    port = int(os.environ.get("APP_PORT", "18035"))
    app.run(host="127.0.0.1", port=port, debug=False)
